### PR TITLE
fix external links with extension md

### LINKED ISSUE #139: .md is removed from external links
e.g.

`[WebAssembly Interface (WIT)](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md)`

is written as

```html
<p>We define the HTTP objects as
<a href="https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT">WebAssembly Interface (WIT)</a>
objects, currently using <em>records</em>:</p>
```

### PR DESCRIPTION
**Pull request by rajatjindal**
fixes #139

### CODE REVIEW

**Comment by rajatjindal** [comment]
instead of testing rendered markdown, I changed the unit test to verify link rewriting to ensure it covers all the scenarios. This is my first time writing unit tests in rust, please let me know if something does not look right.

**Comment by rajatjindal** [comment]
moving  this back to WIP, as following scenario still seems broken

`relative-link.md#some-hash`

it should be rewritten to

`relative-link#some-hash`

**Comment by rajatjindal** [comment]
This is ready for review again

**Review by karthik2804 — COMMENTED** [review]
In the case that I provide an absolute URL with the same `base_url` such as `https://localhost:3000/markdown.md` the `.md` suffix is not trimmed, is this a case we want to handle so as to make the URLs more consistent instead of referring to the same page as `./markdown.md` as well as `/.markdown`. Otherwise the changes look good

**Comment by rajatjindal** [comment]
i think in general using base_url explicitly for same server url is a bad idea in `.md` file e.g. how would it work for scenarios like `localhost`  vs `canary deployment` vs `prod deployment`.

keeping that in mind, I am inclined towards not adding more complexity for this particular scenario. but I could be convinced otherwise too :)

Thanks
Rajat Jindal

**Comment by karthik2804** [comment]
@rajatjindal I agree but I'm just wondering about the possibility. Not a big concern of mine otherwise the PR looks good.

**Comment by rajatjindal** [comment]
yeah, I would say lets go with the changes we have so far, and we can recommend user to fix the url to use relative url in such cases for now. 

If we see it becoming a problem that our users bump into frequently, we can always revisit and fix it.

**Review by karthik2804 — APPROVED** [review]

**Comment by rajatjindal** [comment]
thank you @karthik2804

**Pull request merged**
