### PR TITLE
chore(spin.toml): update redirected contributing route

### PR DESCRIPTION
**Pull request by vdice**

### CODE REVIEW

**Comment by vdice** [comment]
Actually, @tpmccallum, I'm wondering if the change should be in the developer repo to update the endpoint to `developer.fermyon.com/bartholomew/contributing` (and thus close this PR) -- thoughts?

**Comment by karthik2804** [comment]
I think this route might change based on how common docs are organized in `developer`.

**Comment by vdice** [comment]
@karthik2804 we've updated spin recently with similar: https://github.com/fermyon/spin/pull/1123

I'd actually like to see the endpoints be `bartholomew/contributing` and `spin/contributing`, but defer to you and @tpmccallum to make the change -- and we can sync up the changes here in tandem.

In the meantime, I'd say we get this in to match what currently exists.  WDYT?

**Comment by karthik2804** [comment]
Oh actually you are correct, contributing to docs is the one that is going to be common I assume, not the code itself,

**Review by karthik2804 — APPROVED** [review]

**Pull request merged**
