### PR TITLE
feat(.github): add build action

### PR DESCRIPTION
**Pull request by vdice**
* Adds a build/test GH action

### CODE REVIEW

**Comment by vdice** [comment]
I was hoping to see a test run of the added yaml on this PR... do we have to explicitly enable/allow?

**Comment by radu-matei** [comment]
Merge and hope the action starts running?

**Comment by vdice** [comment]
I ended up testing this on my fork and there were quite a few changes needed.  Most are straightforward, but I would like reviewers to check the fixes added per `make test` failures.  See https://github.com/fermyon/bartholomew/pull/54/commits/35bb6905752dd35ffa0488bb18b34068f3b5a5ab -- I just fixed exactly per rust compilation suggestion/clippy suggestion.  Do these fixes look right?

(Also needed to run `cargo fmt` for `make test` to succeed.)

Oh, I also created a new `build-release` make target that runs `build` and then runs `wasm-opt`... rather than trying to install/config `wasm-opt` on the CI runner.  It seems like for Linux hosts the binary is only available via a `binaryen` build/installation?  Or is there an easier way?

Tested via https://github.com/vdice/bartholomew/runs/5668731143?check_suite_focus=true

**Review by technosophos — APPROVED** [review]
Checked the things @vdice asked about and reviewed the entire PR. Looks good.

**Pull request merged**
