### PR TITLE
fix relative link parsing

### PR DESCRIPTION
**Pull request by rajatjindal**
still testing the changes out, for some reason unable to run `make test` on my laptop.

### CODE REVIEW

**Comment by rajatjindal** [comment]
| .md format  | href in rendered html |
| ------------- | ------------- |
| `[URL](https://en.wikipedia.org/)`  | `<a href="https://en.wikipedia.org/">URL</a>` |
| `[relative link](./relative.md)`  | `<a href="relative">relative link</a>`  |
| `[relative link](elsewhere.md)` | `<a href="elsewhere">relative link</a>` |
| `[relative deep link](./relatively/deep.md)` | ` <a href="relatively/deep">relative deep link</a>` |
| `[absolute deep link](/absolute/deep.md)` | `<a href="/absolute/deep">absolute deep link</a>` |

**Comment by rajatjindal** [comment]
I will test more tomorrow to ensure it does not break anything.

**Review by dicej — APPROVED** [review]
Looks good to me.  It's possible this might break links that were implicitly absolute, but we should be able to fix those on a case-by-case basis.

**Comment by rajatjindal** [comment]
Thanks for looking at the pr. Could u pls give an example of the link you are referring to. I will add that to the testcase and verify that it works.

Many thanks
Rajat Jindal

**Comment by dicej** [comment]
For example, imagine you have a couple of documents like this:

foo/bar/baz.md
hello.md

And imagine foo/bar/baz.md has a link like `[hello](./hello.md)` in it.  That's a bad link -- it should be `[hello](../../hello.md)` instead, but currently bartholomew will render it so it works because all links are converted to absolute.  With your change, it will no longer work, **but that's ok** because it shouldn't have worked in the first place.  So we just need to fix such cases in the .md files if we find them.

**Comment by rajatjindal** [comment]
thanks for the explanation @dicej . yeah I would also consider that as bad link and that should be fixed in the content itself

**Review by karthik2804 — APPROVED** [review]

**Pull request merged**
