### PR TITLE
convert relative urls to absolute

### PR DESCRIPTION
**Pull request by karthik2804**
address https://github.com/fermyon/developer/issues/481

### CODE REVIEW

**Comment by rajatjindal** [comment]
I am not 100% certain if this is the right fix. we should probably take a step back and see how other tools solve this. Given how common this is, we cannot be the only one running into this problem.

**Comment by karthik2804** [comment]
@rajatjindal that is a good point. I will look around to see if there is a case of people running into similar issues and potential solutions. 

On the other hand, I feel this is the most straightforward way to this issue as making links absolute will ensure the routing works as intended.

**Comment by tpmccallum** [comment]
@rajatjindal and @karthik2804 is it possible to enforce the removal of a trailing slash upon page load i.e. the server renders the page and never allows a trailing slash `/`?

**Comment by itowlson** [comment]
@rajatjindal Can you qualify _why_ you feel this is not the right fix?  Would you have any objections to it as an interim fix if it solves a pain point?  Absolute URLs in the Markdown makes authoring a complete bear trap as links are either broken or go to the production version of a page instead of the local one with your edits.

**Comment by rajatjindal** [comment]
sorry, my comment is not a blocking comment but just a suggestion to check how other tools might be handling this.

**Comment by itowlson** [comment]
Awesome, thanks @rajatjindal!

@karthik2804 any further concerns are is this safe to ship?

**Comment by karthik2804** [comment]
Just a formal review and it should be good to merge @itowlson

**Comment by karthik2804** [comment]
It just needs a formal review and it should be good to ship.

**Comment by itowlson** [comment]
Thanks, though from our conversation elsewhere it sounds like it's not strictly needed after all, as long as authors avoid relative paths?  But I'm happy to review anyway (not that I know anything about Bartholomew but eh).

**Review by itowlson — APPROVED** [review]
I don't feel qualified to review this at a detail level but I assume it's been tested in both local and deployed environments and if so then LGTM.  Thanks!

**Review by rajatjindal — APPROVED** [review]

**Pull request merged**
