### PR TITLE
add implode template function

### LINKED ISSUE #21: Add `implode` template helper
It would be very useful to have an `implode(list<string>)` command.

Example:
```
implode ", " page.head.tags
```

Above would produce `tag1, tag2, tag3`

### PR DESCRIPTION
**Pull request by rajatjindal**
fixes #21

### CODE REVIEW

**Comment by technosophos** [comment]
I was about to close the laptop for the night when I saw this PR come in. I'll give it a closer read tomorrow, but here's what I was thinking. I started this section in the `template.rs` file where we could define some built-in template functions: https://github.com/fermyon/bartholomew/blob/main/src/template.rs#L163-L220

I was thinking it would be nice to add some functions that would be generally useful to template developers, and since the Rust code is compiled, it's a bit faster than the Rhai code.

I hadn't considered just doing all the template functions in Rhai code. That definitely has some pros and cons. For example, while it might be slower to execute, it means that the Bartholomew user could edit functions without having to recompile.

Maybe the right thing division point would be that "utiltiies" (string manipulation, math, formatting, etc) would go in the Rust code while things that dealt with objects like `site` or `page` or `env` would be rhai scripts. What are your thoughts?

I'll look in on this issue tomorrow. Thanks again! This is fabulous!

**Comment by rajatjindal** [comment]
it totally makes sense. (may be we could even implement something like you had with `sprig`).  I've updated the PR with implode implemented in `template.rs`

kindly let me know if this looks ok.

**Review by technosophos — APPROVED** [review]
Excellent! Thanks.

**Comment by technosophos** [comment]
Oh, yeah... a lot of those Sprig functions have been generally usable well beyond Helm. That is a great idea. I'm going to merge this and then open a few issues with various Sprig functions.

**Pull request merged**
