### PR TITLE
update handle bar sprig

### LINKED ISSUE #113: Bartholomew crashes when trying to use `tweet` embed in templates
When running the `.wasm` module compiled from head with `spin` compiled from head as well, using `tweet` in templates leads to a crash.

Bartholomew commit
```
$ git log --pretty=format:'%h' -n 1
fe4a8f0
```

Inserting tweet embed in templates using 
```
{{{ tweet "fermyontech" "1504846517571489794" }}}
```

results in 
```
2022-08-25T13:34:20.417519Z ERROR spin_http_engine: Error processing request: wasm trap: wasm `unreachable` instruction executed
wasm backtrace:
    0: 0x2f86a6 - panic_abort::__rust_start_panic::abort::h7e7eb72c39986e70
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/panic_abort/src/lib.rs:84:17
              - __rust_start_panic
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/panic_abort/src/lib.rs:37:5
    1: 0x2f8141 - rust_panic
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:746:9
    2: 0x2f80be - std::panicking::rust_panic_with_hook::h5af4a166307aff48
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:716:5
    3: 0x2f7324 - std::panicking::begin_panic_handler::{{closure}}::h42a9871ead2de5e8
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
    4: 0x2f7263 - std::sys_common::backtrace::__rust_end_short_backtrace::h42a6bde96d4a4a1f
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
    5: 0x2f7a0e - rust_begin_unwind
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
    6: 0x303aa8 - core::panicking::panic_fmt::h33d7d4c3033d60da
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
    7: 0x30c9c7 - core::result::unwrap_failed::h5d36bed23403009b
                    at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
    8: 0x6eb0e - <unknown>!<handlebars_sprig::tweet::addhelpers::tweet as handlebars::helpers::HelperDef>::call_inner::hfa56b93483603fc2
    9: 0x6dda2 - <unknown>!handlebars::helpers::HelperDef::call::hd2e59b5adfe7095f
   10: 0xa059e - <unknown>!handlebars::render::render_helper::h8b63e1640a9bc7b4
   11: 0x9f1e3 - <unknown>!<handlebars::template::TemplateElement as handlebars::render::Renderable>::render::h833a9e76d78f6162
   12: 0x9ec5f - <unknown>!<handlebars::template::Template as handlebars::render::Renderable>::render::h5e70041664eb9743
   13: 0x46abf - <unknown>!handlebars::registry::Registry::render::h171ee92c86c34fc1
   14: 0x4c088 - <unknown>!bartholomew::template::Renderer::render_template::h34889982b6d70190
   15: 0x346c4 - <unknown>!<bartholomew::bartholomew::SpinHttp as bartholomew::bartholomew::spin_http::SpinHttp>::handle_http_request::h496cf62464b95d45
   16: 0x22dae - <unknown>!handle-http-request
   17: 0x315738 - <unknown>!handle-http-request.command_export
```

### PR DESCRIPTION
**Pull request by rajatjindal**
- fixes #113 

Note: for tweet embedding to work, we also need to add `allowed_http_hosts = ["https://publish.twitter.com"]` to `docs/spin.toml`

e.g.

```
[[component]]
source = "modules/bartholomew.wasm"
id = "bartholomew"
files = [ "content/**/*" , "shortcodes/*" , "templates/*", "scripts/*", "config/*"]
allowed_http_hosts = ["https://publish.twitter.com"]
[component.trigger]
route = "/..."

```

### CODE REVIEW

**Comment by radu-matei** [comment]
I haven't seen this CI failure before, any thoughts on why this happens?

**Comment by karthik2804** [comment]
Might be possibly due to the mismatched SDK version on `handlebar-sprig` and `bartholomew`.

**Comment by karthik2804** [comment]
I have tested it and the source seems to be due to the `rev` of `spin-sdk` and `wit-bindgen-rust`. Bartholomew and `handlebars-sprig` are referring to different versions of wit-bindgen-rust. I have opened a PR addressing it at https://github.com/rajatjindal/bartholomew/pull/1

**Review by karthik2804 — APPROVED** [review]

**Comment by rajatjindal** [comment]
I think i screwed this branch during conflict resolution. opening a new WIP PR (to ensure CLI tests are ok before I mark it as ready for review)

**Comment by karthik2804** [comment]
superseded by #125

**Pull request closed without merging**
