### PR TITLE
prepare for release v0.7.0

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Review by vdice — APPROVED** [review]

**Comment by karthik2804** [comment]
I thought we were doing a 0.6.0 @rajatjindal

**Comment by rajatjindal** [comment]
Yeah, i tagged 0.6.0 without changing versions by mistake. So tagging 0.7.0. Is there any better way to fix this?

**Comment by karthik2804** [comment]
let's delete the tag 0.7.0 and retag as 0.6 0. Being pre 1.0 it seems safe to correct this in this way to preserve historical consistency.

**Comment by rajatjindal** [comment]
alright. i will close this PR then, and open a new one to retag 0.6.0

**Pull request closed without merging**
